# Set history-limit
set-option -g history-limit 25000

# Easily source tmux file
bind-key -r r source-file ~/.config/tmux/tmux.conf \; display-message "~/.config/tmux/tmux.conf reloaded."

# for neovim
set -sg escape-time 10

# enable mouse in tmux
set -g mouse on

set -g status-style "bg=default"

set -g status-bg default
set -g status-position bottom 
set -g status-interval 2
# set -Fg 'status-format[0]' '#{status-format[1]}'
set -g 'status-format[1]' ''
set -g status 2

# PANE SETTINGS
# count the panes from 1
set -g base-index 1
setw -g pane-base-index 1
# set -g pane-border-lines "heavy"

set-option -g status-interval 5
set-option -g automatic-rename on
set-option -g automatic-rename-format '#{b:pane_current_path}'
# set-option -g automatic-rename-format "#(hostname -I | awk '{print $1}')"

set-option -g focus-events on

set-option -g default-terminal "screen-256color"
set-option -sa terminal-features ',xterm-256color:RGB'
#
#
# PLUGINS
#
set -g @plugin "tmux-plugins/tpm"
set -g @plugin "tmux-plugins/tmux-sensible"
set -g @plugin "tmux-plugins/tmux-resurrect"
set -g @plugin "tmux-plugins/tmux-continuum"
set -g @plugin 'erikw/tmux-powerline'
# init tmux plugin manage
run "$XDG_CONFIG_HOME/tmux/plugins/tpm/tpm"


# set-window-option -g window-status-current-style bg=black
